use_frameworks!

platform :ios, '11.0'

target 'ConfigurationBasedButton_Example' do
  pod 'ConfigurationBasedButton', :path => '../'

  target 'ConfigurationBasedButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
